services:
  - type: web
    name: fungus-back
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Si tienes otras variables de entorno, puedes agregarlas aquí 